# Generated by Django 5.2.8 on 2025-11-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('release_date', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
